-- Split the billboards table along the questions it was answering at once.
--
-- 1. `status` answered two things: whether the board is free (available,
--    busy, reserved, inactive) and whether the listing has passed review
--    (pending, awaiting_payment, needs_revision, rejected). It becomes two
--    columns, `availability` and `moderation`. A row in a review state keeps
--    that state as its moderation and is `available`; every other row is
--    `approved` and keeps its status as its availability.
--
-- 2. The crawler's bookkeeping (url, structureCode, scrapedAt, the sync
--    snapshot, missingSince) moves to `billboard_sources`, one row per crawled
--    billboard. Listings and admin-created rows have no source and get none.
--
-- 3. Columns nothing reads are dropped: `icon` (the UI draws the type's own
--    icon), `mapX`/`mapY` (percentages on a decorative map that was replaced
--    by real coordinates), and `ownerId` with the `owners` table, which no
--    write path ever populated outside the demo seed.
--
-- 4. Review replies and audit rows get real foreign keys for their actor:
--    `review_replies.staffId` → admins, `audit_logs.userId` → users. Audit
--    rows written before `adminId` was filled in carried the actor in
--    details.actorId; those are linked where the account still exists.
--
-- Generated by `prisma migrate diff`, then edited where marked "hand-written":
-- SQLite rebuilds a table to drop a column, so the data moves have to happen
-- while the old table still exists, and the partial unique index Prisma cannot
-- see (20260902140000) has to be recreated on the rebuilt table.

-- DropTable
PRAGMA foreign_keys=off;
DROP TABLE "owners";
PRAGMA foreign_keys=on;

-- CreateTable
CREATE TABLE "billboard_sources" (
    "billboardId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "url" TEXT,
    "structureCode" TEXT,
    "scrapedAt" TEXT,
    "snapshot" JSONB,
    "missingSince" DATETIME,
    CONSTRAINT "billboard_sources_billboardId_fkey" FOREIGN KEY ("billboardId") REFERENCES "billboards" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- hand-written: every crawled row's bookkeeping, before its columns are dropped.
INSERT INTO "billboard_sources" ("billboardId", "url", "structureCode", "scrapedAt", "snapshot", "missingSince")
SELECT "id", "url", "structureCode", "scrapedAt", "sourceSnapshot", "missingSince"
FROM "billboards"
WHERE "source" IS NOT NULL AND "source" NOT IN ('listing', 'manual');

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_audit_logs" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "timestamp" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "action" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "adminId" INTEGER,
    "userId" INTEGER,
    "userEmail" TEXT,
    "ip" TEXT,
    "userAgent" TEXT,
    "details" JSONB,
    CONSTRAINT "audit_logs_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "admins" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "audit_logs_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_audit_logs" ("action", "adminId", "details", "id", "ip", "severity", "timestamp", "userAgent", "userEmail") SELECT "action", "adminId", "details", "id", "ip", "severity", "timestamp", "userAgent", "userEmail" FROM "audit_logs";
DROP TABLE "audit_logs";
ALTER TABLE "new_audit_logs" RENAME TO "audit_logs";
CREATE INDEX "audit_logs_adminId_idx" ON "audit_logs"("adminId");
CREATE INDEX "audit_logs_userId_idx" ON "audit_logs"("userId");
CREATE INDEX "audit_logs_timestamp_idx" ON "audit_logs"("timestamp");
CREATE TABLE "new_billboards" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "availability" TEXT NOT NULL DEFAULT 'available',
    "moderation" TEXT NOT NULL DEFAULT 'approved',
    "width" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "faces" INTEGER NOT NULL,
    "age" INTEGER NOT NULL,
    "area" INTEGER NOT NULL DEFAULT 0,
    "price" INTEGER NOT NULL,
    "priceWeekly" INTEGER NOT NULL,
    "priceQuarterly" INTEGER NOT NULL,
    "priceYearly" INTEGER NOT NULL,
    "traffic" JSONB NOT NULL,
    "estimatedViews" INTEGER NOT NULL DEFAULT 0,
    "lat" REAL,
    "lng" REAL,
    "hasImages" BOOLEAN NOT NULL DEFAULT false,
    "images" JSONB NOT NULL,
    "allImages" JSONB,
    "agency" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "features" JSONB NOT NULL,
    "nearbyLandmarks" JSONB NOT NULL,
    "rating" REAL NOT NULL,
    "reviewCount" INTEGER NOT NULL,
    "source" TEXT,
    "submittedById" INTEGER,
    "reviewNote" TEXT,
    "plan" TEXT NOT NULL DEFAULT 'free',
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "billboards_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_billboards" ("availability", "moderation", "age", "agency", "allImages", "area", "city", "createdAt", "description", "estimatedViews", "faces", "featured", "features", "hasImages", "height", "id", "images", "lat", "lng", "location", "name", "nearbyLandmarks", "phone", "plan", "price", "priceQuarterly", "priceWeekly", "priceYearly", "rating", "region", "reviewCount", "reviewNote", "slug", "source", "submittedById", "traffic", "type", "updatedAt", "width") SELECT
    -- hand-written: the one status column, split into its two questions.
    CASE WHEN "status" IN ('available', 'busy', 'reserved', 'inactive') THEN "status" ELSE 'available' END,
    CASE WHEN "status" IN ('pending', 'awaiting_payment', 'needs_revision', 'rejected') THEN "status" ELSE 'approved' END,
    "age", "agency", "allImages", "area", "city", "createdAt", "description", "estimatedViews", "faces", "featured", "features", "hasImages", "height", "id", "images", "lat", "lng", "location", "name", "nearbyLandmarks", "phone", "plan", "price", "priceQuarterly", "priceWeekly", "priceYearly", "rating", "region", "reviewCount", "reviewNote", "slug", "source", "submittedById", "traffic", "type", "updatedAt", "width" FROM "billboards";
DROP TABLE "billboards";
ALTER TABLE "new_billboards" RENAME TO "billboards";
CREATE UNIQUE INDEX "billboards_slug_key" ON "billboards"("slug");
CREATE INDEX "billboards_city_idx" ON "billboards"("city");
CREATE INDEX "billboards_type_idx" ON "billboards"("type");
CREATE INDEX "billboards_moderation_availability_idx" ON "billboards"("moderation", "availability");
CREATE INDEX "billboards_price_idx" ON "billboards"("price");
CREATE INDEX "billboards_submittedById_idx" ON "billboards"("submittedById");
CREATE INDEX "billboards_hasImages_idx" ON "billboards"("hasImages");
CREATE INDEX "billboards_featured_hasImages_price_idx" ON "billboards"("featured", "hasImages", "price");
CREATE INDEX "billboards_hasImages_price_idx" ON "billboards"("hasImages", "price");
CREATE INDEX "billboards_hasImages_estimatedViews_idx" ON "billboards"("hasImages", "estimatedViews");
CREATE INDEX "billboards_hasImages_area_idx" ON "billboards"("hasImages", "area");
CREATE INDEX "billboards_city_moderation_idx" ON "billboards"("city", "moderation");
CREATE INDEX "billboards_city_type_idx" ON "billboards"("city", "type");
CREATE INDEX "billboards_type_price_idx" ON "billboards"("type", "price");
CREATE INDEX "billboards_lat_lng_idx" ON "billboards"("lat", "lng");
-- hand-written: rebuilt table, so the duplicate-listing guard is recreated
-- (see 20260902140000_listing_submit_unique).
CREATE UNIQUE INDEX "listings_submitter_name_city_key"
    ON "billboards" ("submittedById", "name", "city")
    WHERE "source" = 'listing' AND "submittedById" IS NOT NULL;
CREATE TABLE "new_review_replies" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "reviewId" INTEGER NOT NULL,
    "userId" INTEGER,
    "staffId" INTEGER,
    "authorName" TEXT NOT NULL,
    "isStaff" BOOLEAN NOT NULL DEFAULT false,
    "body" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "review_replies_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "reviews" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "review_replies_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "review_replies_staffId_fkey" FOREIGN KEY ("staffId") REFERENCES "admins" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_review_replies" ("authorName", "body", "createdAt", "id", "isStaff", "reviewId", "userId") SELECT "authorName", "body", "createdAt", "id", "isStaff", "reviewId", "userId" FROM "review_replies";
DROP TABLE "review_replies";
ALTER TABLE "new_review_replies" RENAME TO "review_replies";
CREATE INDEX "review_replies_reviewId_createdAt_idx" ON "review_replies"("reviewId", "createdAt");
CREATE INDEX "review_replies_userId_idx" ON "review_replies"("userId");
CREATE INDEX "review_replies_staffId_idx" ON "review_replies"("staffId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- hand-written: link past audit rows to the staff account they recorded.
UPDATE "audit_logs"
SET "adminId" = CAST(json_extract("details", '$.actorId') AS INTEGER)
WHERE "adminId" IS NULL
  AND json_extract("details", '$.actorId') IN (SELECT "id" FROM "admins");
